# Stable Options
edition = "2018"
fn_args_layout = "Compressed"
force_explicit_abi = true
hard_tabs = true
max_width = 120
merge_derives = true
newline_style = "Native"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = false

# Unstable
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
combine_control_expr = true
empty_item_single_line = true
enum_discrim_align_threshold = 8
fn_single_line = true
comment_width = 80
trailing_comma = "Vertical"
match_block_trailing_comma = true
match_arm_blocks = true
merge_imports = false
normalize_comments = false
